### ISSUE TITLE
Highlighting is inconsistent

### ISSUE THREAD

**Issue by jbs87** [twg/wikiwash#62] opened 2015-01-14 16:18 UTC
Clicking the add/remove for edits is inconsistent. For some of them, the highlighting correctly turns on and off. For others, the highlighting does not come back.

On page load

![screen shot 2015-01-14 at 11 17 16 am](https://cloud.githubusercontent.com/assets/9323929/5742292/fdb09592-9bde-11e4-9a77-c9f8833f98f7.png)

On unchecking and rechecking add and remove
![screen shot 2015-01-14 at 11 17 33 am](https://cloud.githubusercontent.com/assets/9323929/5742304/0e764b4c-9bdf-11e4-9783-19942d0f3ce6.png)

Chrome Version 39.0.2171.95 (64-bit)
MAC OSX

**Comment by irfanpirbhai** [comment] 2015-03-24 00:14
Dupe of #47.

**Closed by irfanpirbhai** 2015-03-24 00:14 UTC
Labels: i-in jira
