### ISSUE TITLE
Multiple meaning words produce redirect links in system can't function

### ISSUE THREAD

**Issue by grandchao** [twg/wikiwash#54] opened 2014-12-13 01:06 UTC
system: windows 8
browser: google Chrome Version 39.0.2171.65 m

description: For example, when input "abc" into input bar. System redirect to a link like shows:
![2 1](https://cloud.githubusercontent.com/assets/10171585/5421821/fb035c3a-8239-11e4-9df3-a3e1fee596d5.png)

which is not the same link as shown in wikipedia. 
![2 2](https://cloud.githubusercontent.com/assets/10171585/5421822/07826f0a-823a-11e4-8cdd-2d4c2437c46c.png)

That is because "abc" is a multiple meaning words, which have many choices in wikipedia.

Click on the link given from wikiwash, it will also produce error message shown like this:
![2 3](https://cloud.githubusercontent.com/assets/10171585/5421833/3263133c-823a-11e4-8995-72152a80ca49.png)

Any words input can produce redirect links, functionality is not working.

**Comment by irfanpirbhai** [comment] 2015-03-24 00:08
Unable to reproduce. Marking as **Resolved**.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution

**Closed by irfanpirbhai** 2015-03-24 00:08 UTC
Labels: i-in jira
