### ISSUE TITLE
Double click the Remove/Added checkbox could not produce the same screen, for some wikipedia url only 

### ISSUE THREAD

**Issue by grandchao** [twg/wikiwash#56] opened 2014-12-13 06:59 UTC
system: windows 8
browser: google Chrome Version 39.0.2171.65 m
description: 
This defects only happen for some input words, not for all words. For example, when I typed wikipedia link url for "December 2014" into the input bar, results show like this:
![4 1](https://cloud.githubusercontent.com/assets/10171585/5422913/b14433a4-826a-11e4-9279-718d9d401e3c.png)
When I clicked off the added checkbox (green), system show like this:
![4 2](https://cloud.githubusercontent.com/assets/10171585/5422917/ed58aa64-826a-11e4-8f7f-f77984137571.png)

when I clicked on again the added checkbox (green), the added texts are not in green color. Not the same as first image. 
![4 3](https://cloud.githubusercontent.com/assets/10171585/5422920/145b4a04-826b-11e4-800b-5fdae5091a9e.png)

Same problems happen as I clicked off the removed checkbox (red), and clicked on again. The shown screen are not in red color. 
![4 4](https://cloud.githubusercontent.com/assets/10171585/5422922/45caeac2-826b-11e4-837a-2f488186564e.png)

**Comment by irfanpirbhai** [comment] 2015-03-24 00:09
Dupe of #47.

**Closed by irfanpirbhai** 2015-03-24 00:09 UTC
Labels: i-in jira
