### ISSUE TITLE
Back button freezes the website

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#93] opened 2015-03-12 18:36 UTC
- Whenever we click on wash and then click back button (browser or keyboard) the website goes into an endless loading loop and then all the edits on the left disappear
- Clicking on the back button again would behave as usual and is returned to the home page

**Comment by tadman** [comment] 2015-03-16 15:14
Duplicate of #49.

**Closed by tadman** 2015-03-16 15:14 UTC
