### ISSUE TITLE
All Browsers: User has to click back button twice in order to go back to homepage

### ISSUE THREAD

**Issue by YangPanQA** [twg/wikiwash#78] opened 2015-01-29 20:00 UTC
Tested on IE 11.0.9600.175.01 Firefox 35.0.1 Chrome 40.0.2214.94 m (Both desktop and mobile)
and Safari on iOS 7.1.2
Steps to reproduce the issue:
1. go to http://wikiwash.metronews.ca/
2. make any valid search (ex.2015 Africa Cup of Nations)
3. click wash button
4. click/press back button on the browser

expected result: The page should be back to homepage after clicking the back button
actual result: User has to click back button twice in order to go back to homepage. After the first click, user is able to see two "W" letters rotating and not going back to the homepage. 

Attached the screenshot after clicking back button at first time.
![clickonce](https://cloud.githubusercontent.com/assets/10762373/5965057/07504c16-a7c7-11e4-83f1-2b4f02c4adda.png)

**Comment by tadman** [comment] 2015-03-11 22:19
Duplicate of Issue #49

**Closed** 2015-03-23 18:43 UTC
Labels: jira, review
