### ISSUE TITLE
In IE version 11 check boxes for added/removed don't actually appear to check despite behaving as though they were

### ISSUE THREAD

**Issue by Zajajajaja** [twg/wikiwash#67] opened 2015-01-15 15:32 UTC
![image](https://cloud.githubusercontent.com/assets/10548253/5760322/b4c3cffc-9ca1-11e4-9b8c-fbd5c236781e.png)

**Comment by irfanpirbhai** [comment] 2015-03-24 00:18
Unable to reproduce. Marking as resolved.

**Tested on:**
- Windows 8.1, IE 11, 1366 x 768 resolution (via BrowserStack)

**Closed by irfanpirbhai** 2015-03-24 00:18 UTC
Labels: i-in jira
