### ISSUE TITLE
Caption/Wikipedia URL format in the text box

### ISSUE THREAD

**Issue by Mkhoury** [twg/wikiwash#97] opened 2015-03-12 18:44 UTC
- Entering the following link in the text box works just fine http://en.wikipedia.org/wiki/Test. If we remove the "en" from that link  the website doesn't resolve it and gives an error knowing that the mentioned link is a valid link if we open it in the browser

Confusing caption for the text box:
- The sentence "paste a url in the text box" is misleading cos we can write the articles title and still see the washed article as if we pasted the url. In my opinion this should be something like "Paste a Wikipedia URL/Title to wash"

**Comment by tadman** [comment] 2015-03-16 17:47
Duplicate of #84.

**Closed by tadman** 2015-03-16 17:47 UTC
