### ISSUE TITLE
Real-time update animation repeats several times

### ISSUE THREAD

**Issue by tadman** [twg/wikiwash#102] opened 2015-03-17 19:30 UTC
The slide-down effect when an edit has been made shows up several times, the same element repeating its animation.

To test, edit the Wikipedia sandbox page: http://en.wikipedia.org/wiki/Wikipedia:Sandbox

**Comment by irfanpirbhai** [comment] 2015-03-25 17:23
Dupe of #85. Let's let the issue live there.

**Closed by irfanpirbhai** 2015-03-25 17:23 UTC
Labels: a-article page, a-css, a-UI, p-minor, t-bug
