### ISSUE TITLE
Input sign into inputbox produce the redirect links which can occur errors when clicking it

### ISSUE THREAD

**Issue by grandchao** [twg/wikiwash#53] opened 2014-12-13 00:27 UTC
system: windows 8
browser: google Chrome Version 39.0.2171.65 m

description: when I input "@" into the inputbox, there produce redirect links to click. 
![1](https://cloud.githubusercontent.com/assets/10171585/5421550/15f16ff6-8234-11e4-9a08-ff76ede7cbc1.png)

Click the "at sign" will cause error message "An error occurred"
![2](https://cloud.githubusercontent.com/assets/10171585/5421568/6bfcbb26-8234-11e4-91f3-9e73005334cd.png)

While if type "at sign" instead of clicking the redirect link, page will load to the same page as where wikipedia shows. 
![3](https://cloud.githubusercontent.com/assets/10171585/5421583/a408a91c-8234-11e4-92db-84cb9794b763.png)

![4](https://cloud.githubusercontent.com/assets/10171585/5421592/b3bb78d0-8234-11e4-8aa8-cc5d9a255aa2.png)

So the redirect link is a defeat need to be fixed.

**Comment by irfanpirbhai** [comment] 2015-03-24 00:07
Unable to reproduce. Marking as **Resolved**.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution

**Closed by irfanpirbhai** 2015-03-24 00:07 UTC
Labels: i-in jira
