### ISSUE TITLE
Some texts no color shown when removed/added done

### ISSUE THREAD

**Issue by grandchao** [twg/wikiwash#57] opened 2014-12-13 07:17 UTC
system: windows 8
browser: google Chrome Version 39.0.2171.65 m
description: Type "toronto" into input box, the pages left corner indicate 930 added texts, but there is no green colors shown on texts where have been added. 
![5 1](https://cloud.githubusercontent.com/assets/10171585/5422978/1c0bdc84-826e-11e4-8e78-cf044924b1e7.png)

**Comment by irfanpirbhai** [comment] 2015-03-24 00:12
No longer able to reproduce this issue, as the referenced edit has been pushed out of view on WikiWash. Marking as **Cannot Reproduce**. Feel free to re-open this issue if the problem appears again.

**Tested on:**
- OSX Yosemite, Chrome 41.0, 1366x768 resolution

**Closed by irfanpirbhai** 2015-03-24 00:12 UTC
Labels: i-in jira
